# Generated by Django 2.2.28 on 2022-11-12 12:40

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(max_length=7, null=True, verbose_name='Цвет')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'теги',
                'ordering': ('name',),
            },
            bases=(models.Model, recipes.validators.ValidateSlug),
        ),
    ]
